---
input:
  type: RosInput
  tf_verbosity: 1
  clear_queue_on_fail: true
  inputs:
    left_cam:
      receiver: {type: ClosedSetImageReceiver}
      sensor: {type: camera_info, min_range: 0.1, max_range: 5.0, extrinsics: {type: ros, robot_frame: base_link_gt}}
features: {type: FeatureReceiver}
